from utils.resource_path import get_resource_path

TITLE = "Breakout"
FPS = 60

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
HUD_HEIGHT = 50

ASSETS_DIR = get_resource_path("assets")
LEVELS_DIR = get_resource_path(ASSETS_DIR / "levels")
SOUNDS_DIR = get_resource_path(ASSETS_DIR / "sounds")

EXP_BASE = 100
EXP_GROWTH = 1.5
PLAYER_MAX_SPEED = 600
PLAYER_ACCELERATION = 10000
PLAYER_FRICTION = 5000
PLAYER_WIDTH = 120
PLAYER_HEIGHT = 8
MAX_ANGLE = 250

BALL_SIZE = 12
BALL_ACCELERATION = 400
BALL_MAX_SPEED = 450

BLOCK_WIDTH = 90
BLOCK_HEIGHT = 40
BLOCK_SPACING = 8

DAMAGE_ZONE_HEIGHT = 10
